/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

public class AcercaDe extends javax.swing.JFrame {

    String user;
    int session_user;

    public AcercaDe() {
        initComponents();
        user = Login.user;
        session_user = Administrador.session_user;

        setSize(400, 300);
        setResizable(false);
        setTitle("Acerca de - Sesión de " + user);
        setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icon);
        this.repaint();

        if (session_user == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icon-40px.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_userName1 = new javax.swing.JLabel();
        label_userName2 = new javax.swing.JLabel();
        label_userName3 = new javax.swing.JLabel();
        label_acercaDe = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_userName1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label_userName1.setForeground(new java.awt.Color(255, 255, 255));
        label_userName1.setText("Challenge Alura-Latam");
        getContentPane().add(label_userName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 60, -1, -1));

        label_userName2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label_userName2.setForeground(new java.awt.Color(255, 255, 255));
        label_userName2.setText("https://github.com/MrlnTrrzs13");
        getContentPane().add(label_userName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 170, 204, -1));

        label_userName3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        label_userName3.setForeground(new java.awt.Color(255, 255, 255));
        label_userName3.setText("Desarrollado por Marlon Torres");
        getContentPane().add(label_userName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 220, 167, -1));

        label_acercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acerca_de.jpg"))); // NOI18N
        getContentPane().add(label_acercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 90, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            java.awt.EventQueue.invokeLater(() -> {
                new AcercaDe().setVisible(true);
            });
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_acercaDe;
    private javax.swing.JLabel label_userName1;
    private javax.swing.JLabel label_userName2;
    private javax.swing.JLabel label_userName3;
    private javax.swing.JLabel label_wallpaper;
    // End of variables declaration//GEN-END:variables
}
