package views;

import controller.UsuarioController;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import model.Usuario;

public final class Administrador extends javax.swing.JFrame {

    String user;
    public static int session_user;
    private final UsuarioController userController;

    public Administrador() {
        this.userController = new UsuarioController();
        initComponents();
        user = Login.user;
        session_user = 1;
        setSize(841, 550);
        setResizable(false);
        setTitle("Administrador - Sesión de " + user);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        ImageIcon log = new ImageIcon("src/images/Ha-100px.png");
        Icon icon_log = new ImageIcon(log.getImage().getScaledInstance(label_log.getWidth(),
                label_log.getHeight(), Image.SCALE_DEFAULT));
        label_log.setIcon(icon_log);
        this.repaint();

        ImageIcon background = new ImageIcon("src/images/admin.png");
        Icon icon_background = new ImageIcon(background.getImage().getScaledInstance(label_background.getWidth(),
                label_background.getHeight(), Image.SCALE_DEFAULT));
        label_background.setIcon(icon_background);
        this.repaint();        
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icon);
        this.repaint();
        
        NameUsers();
    }

    private List<Usuario> NameUser() {
        return this.userController.SearchNameAdmin(user);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icon-40px.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_userName = new javax.swing.JLabel();
        label_log = new javax.swing.JLabel();
        btn_registerUser = new javax.swing.JButton();
        label_registerUser = new javax.swing.JLabel();
        btn_registerHues = new javax.swing.JButton();
        label_registerHues = new javax.swing.JLabel();
        btn_gestUser = new javax.swing.JButton();
        label_gestUser = new javax.swing.JLabel();
        btn_reservation = new javax.swing.JButton();
        label_reservation = new javax.swing.JLabel();
        btn_gestHuesp = new javax.swing.JButton();
        label_gestHuesp = new javax.swing.JLabel();
        btn_capturist = new javax.swing.JButton();
        label_capturist = new javax.swing.JLabel();
        label_footer = new javax.swing.JLabel();
        btn_about = new javax.swing.JButton();
        label_about = new javax.swing.JLabel();
        label_background = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_userName.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        label_userName.setForeground(new java.awt.Color(255, 255, 255));
        label_userName.setText("User");
        getContentPane().add(label_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
        getContentPane().add(label_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 100, 100));

        btn_registerUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        btn_registerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerUserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registerUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 170, 120, 100));

        label_registerUser.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_registerUser.setForeground(new java.awt.Color(0, 51, 51));
        label_registerUser.setText("Registrar Usuario");
        getContentPane().add(label_registerUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        btn_registerHues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_registerHues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerHuesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registerHues, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 170, 120, 100));

        label_registerHues.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_registerHues.setForeground(new java.awt.Color(0, 0, 0));
        label_registerHues.setText("Registrar Huésped");
        getContentPane().add(label_registerHues, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 270, -1, -1));

        btn_gestUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        btn_gestUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestUserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gestUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 170, 120, 100));

        label_gestUser.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_gestUser.setForeground(new java.awt.Color(0, 51, 51));
        label_gestUser.setText("Gestionar Usuario");
        getContentPane().add(label_gestUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 270, -1, -1));

        btn_reservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reservation.png"))); // NOI18N
        btn_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 170, 120, 100));

        label_reservation.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_reservation.setForeground(new java.awt.Color(0, 51, 51));
        label_reservation.setText("Reservasión");
        getContentPane().add(label_reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 270, -1, -1));

        btn_gestHuesp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        btn_gestHuesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestHuespActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gestHuesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 340, 120, 100));

        label_gestHuesp.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_gestHuesp.setForeground(new java.awt.Color(102, 102, 102));
        label_gestHuesp.setText("Gestionar Huésped");
        getContentPane().add(label_gestHuesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 440, -1, -1));

        btn_capturist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capturista.png"))); // NOI18N
        btn_capturist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capturistActionPerformed(evt);
            }
        });
        getContentPane().add(btn_capturist, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 120, 100));

        label_capturist.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_capturist.setForeground(new java.awt.Color(102, 102, 102));
        label_capturist.setText("Panel Vista Capturista");
        getContentPane().add(label_capturist, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        label_footer.setBackground(new java.awt.Color(102, 102, 102));
        label_footer.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        label_footer.setForeground(new java.awt.Color(102, 102, 102));
        label_footer.setText("Desarrollado por Marlon Torres © 2023");
        getContentPane().add(label_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 500, 242, -1));

        btn_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acerca_de.jpg"))); // NOI18N
        btn_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 340, 120, 100));

        label_about.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_about.setForeground(new java.awt.Color(102, 102, 102));
        label_about.setText("Acerca de");
        getContentPane().add(label_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 440, -1, -1));
        getContentPane().add(label_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 75, 350, 400));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 841, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gestHuespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestHuespActionPerformed
        GestionarHuesped gestionsGuest = new GestionarHuesped();
        gestionsGuest.setVisible(true);
    }//GEN-LAST:event_btn_gestHuespActionPerformed

    private void btn_registerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerUserActionPerformed
        RegistroUsuario registrerUser = new RegistroUsuario();
        registrerUser.setVisible(true);
    }//GEN-LAST:event_btn_registerUserActionPerformed

    private void btn_registerHuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerHuesActionPerformed
        RegistroHuesped register = new RegistroHuesped(0);
        register.setVisible(true);
    }//GEN-LAST:event_btn_registerHuesActionPerformed

    private void btn_gestUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestUserActionPerformed
        GestionarUsuarios infoUser = new GestionarUsuarios();
        infoUser.setVisible(true);
    }//GEN-LAST:event_btn_gestUserActionPerformed

    private void btn_capturistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capturistActionPerformed
        Capturista capturist = new Capturista();
        capturist.setVisible(true);
    }//GEN-LAST:event_btn_capturistActionPerformed

    private void btn_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutActionPerformed
        AcercaDe about = new AcercaDe();
        about.setVisible(true);
    }//GEN-LAST:event_btn_aboutActionPerformed

    private void btn_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservationActionPerformed
        RegistroReservas reservation = new RegistroReservas();
        reservation.setVisible(true);
    }//GEN-LAST:event_btn_reservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            java.awt.EventQueue.invokeLater(() -> {
                new Administrador().setVisible(true);
            });
        } catch (Exception e) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_about;
    private javax.swing.JButton btn_capturist;
    private javax.swing.JButton btn_gestHuesp;
    private javax.swing.JButton btn_gestUser;
    private javax.swing.JButton btn_registerHues;
    private javax.swing.JButton btn_registerUser;
    private javax.swing.JButton btn_reservation;
    private javax.swing.JLabel label_about;
    private javax.swing.JLabel label_background;
    private javax.swing.JLabel label_capturist;
    private javax.swing.JLabel label_footer;
    private javax.swing.JLabel label_gestHuesp;
    private javax.swing.JLabel label_gestUser;
    private javax.swing.JLabel label_log;
    private javax.swing.JLabel label_registerHues;
    private javax.swing.JLabel label_registerUser;
    private javax.swing.JLabel label_reservation;
    private javax.swing.JLabel label_userName;
    private javax.swing.JLabel label_wallpaper;
    // End of variables declaration//GEN-END:variables

    private void NameUsers() {
        List <Usuario> users = NameUser();
        try {
            for(Usuario user_Name : users) {
                String user_name = user_Name.getName();
                label_userName.setText("Bienvenido " + user_name);
            }
        } catch (Exception e) {
        }
    }
}
