package views;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import model.Huesped;
import controller.HuespedController;
import java.util.List;

public class GestionarHuesped extends javax.swing.JFrame {

    String user;
    int userSession = 0, session_user = 0;
    public static int id_huespedUp = 0;
    DefaultTableModel model = new DefaultTableModel();
    private final HuespedController guestController;

    public GestionarHuesped() {
        this.guestController = new HuespedController();
        
        userSession = Capturista.userSession;
        session_user = Administrador.session_user;
        initComponents();
        user = Login.user;

        setSize(630, 330);
        setTitle("Capturista - Sesión de " + user);
        setResizable(false);
        setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icon);
        this.repaint();
        
        if (session_user == 1 || userSession == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        table_huesped = new JTable(model);
        jScrollPane1.setViewportView(table_huesped);
        
        model.addColumn(" ");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Telefono");
        model.addColumn("Fecha de nacimiento");
        model.addColumn("Nacionalidad");
        model.addColumn("Id_reserva");
        table_huesped.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        fillTable();

        table_huesped.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row_point = table_huesped.rowAtPoint(e.getPoint());
                int column_point = 0;

                if (row_point > -1) {
                    id_huespedUp = (int) model.getValueAt(row_point, column_point);
                    InformacionHuesped informationHuesped = new InformacionHuesped();
                    informationHuesped.setVisible(true);
                }
            }
        });
    }

    private List<Huesped> Search() {
        return this.guestController.ToListGuest();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icon-40px.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titleManageClients = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_huesped = new javax.swing.JTable();
        label_wallpaper = new javax.swing.JLabel();
        label_footer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titleManageClients.setFont(new java.awt.Font("DejaVuSansMono Nerd Font", 1, 24)); // NOI18N
        label_titleManageClients.setForeground(new java.awt.Color(255, 255, 255));
        label_titleManageClients.setText("Huéspedes Registrados");
        getContentPane().add(label_titleManageClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 20, 295, -1));

        table_huesped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_huesped);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 630, 180));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 330));

        label_footer.setBackground(new java.awt.Color(102, 102, 102));
        label_footer.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        label_footer.setForeground(new java.awt.Color(102, 102, 102));
        label_footer.setText("Desarrollado por Marlon Torres © 2023");
        getContentPane().add(label_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 300, 242, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            java.awt.EventQueue.invokeLater(() -> {
                new GestionarHuesped().setVisible(true);
            });
        } catch (Exception e) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_footer;
    private javax.swing.JLabel label_titleManageClients;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JTable table_huesped;
    // End of variables declaration//GEN-END:variables

    private void fillTable() {
        List<Huesped> guest = Search();
        try {
            for (Huesped guests : guest) {
                model.addRow(new Object[]{guests.getId(), guests.getName(),
                    guests.getLastName(), guests.getPhone(), guests.getbirthdate(), 
                    guests.getNationality(), guests.getIdReservation()});
            }
        } catch (Exception e) {
            throw e;
        }
    }
}
