package views;

import controller.UsuarioController;
import factory.Conexion;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import model.Usuario;

public class Informacion extends javax.swing.JFrame {
    
    private String user, name_user;
    private int session_user;
    private final UsuarioController userController;
    
    public Informacion() {
        initComponents();
        user = Login.user;
        session_user = Administrador.session_user;
        session_user = Capturista.userSession;
        this.userController = new UsuarioController();
        
        setSize(680, 480);
        setResizable(false);
        setTitle("Informacion del Programa - Sesión de " + user);
        setLocationRelativeTo(null);

        ImageIcon log = new ImageIcon("src/images/Logo-150px.png");
        Icon icon_log = new ImageIcon(log.getImage().getScaledInstance(label_log.getWidth(),
                label_log.getHeight(), Image.SCALE_DEFAULT));
        label_log.setIcon(icon_log);
        this.repaint();
               
        ImageIcon backgrd = new ImageIcon("src/images/fondo_blanco.jpg");
        Icon icon_background = new ImageIcon(backgrd.getImage().getScaledInstance(label_background.getWidth(),
                label_background.getHeight(), Image.SCALE_DEFAULT));
        label_background.setIcon(icon_background);
        this.repaint();
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icon);
        this.repaint();
        
        if (session_user == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        try {
            Search();

        } catch (Exception e) {
            System.out.println("ERROR en consultar nombre del capturista.");
        }
    }

    private List<Usuario> SearchUser() {
        return this.userController.SearchNameAdmin(user);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_log = new javax.swing.JLabel();
        label_title = new javax.swing.JLabel();
        label_welcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_background = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(label_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 46, 150, 150));

        label_title.setBackground(java.awt.SystemColor.window);
        label_title.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        label_title.setForeground(new java.awt.Color(0, 51, 204));
        label_title.setText("Sistema de Reservas                                              Año: 2023");
        getContentPane().add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 120));

        label_welcome.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        label_welcome.setText("Bienvenido.");
        getContentPane().add(label_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel1.setText("Sistema de reserva de hotel. ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel2.setText("Controle y administre de forma óptima y fácil el flujo de reservas y de huespédes del hotel.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel3.setText("Esta herramienta le permitirá llevar un control completo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel4.setText("y detallado de sus reservas y huéspedes, tendrá acceso a heramientas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setText("especiales para tareas específicas como lo son:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 2, 16)); // NOI18N
        jLabel6.setText("- Registro de Reservas y Huéspedes.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setText("- Edición de Reservas y Huéspedes existentes.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 2, 16)); // NOI18N
        jLabel8.setText("- Eliminar todo tipo de registros.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        label_background.setBackground(java.awt.SystemColor.window);
        getContentPane().add(label_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 680, 260));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 680, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            java.awt.EventQueue.invokeLater(() -> {
                new Informacion().setVisible(true);
            });
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_background;
    private javax.swing.JLabel label_log;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JLabel label_welcome;
    // End of variables declaration//GEN-END:variables

    private void Search(){
        List<Usuario> users = SearchUser();
        for (Usuario User : users) {
            name_user = User.getName();
            label_welcome.setText("Hola " + name_user);
        }
    }
}
