package views;

import java.awt.EventQueue;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        setSize(910, 537);
        setResizable(false);
        setTitle("Hotel Alura");
        setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/images/menu-img.png");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icon);
        this.repaint();

        ImageIcon log = new ImageIcon("src/images/Logo-150px.png");
        Icon icon_log = new ImageIcon(log.getImage().getScaledInstance(label_log.getWidth(),
                label_log.getHeight(), Image.SCALE_DEFAULT));
        label_log.setIcon(icon_log);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icon-40px.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_log = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        label_login = new javax.swing.JLabel();
        label_footer = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_log.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(label_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 150, 150));

        btn_login.setBackground(java.awt.SystemColor.window);
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        btn_login.setContentAreaFilled(false);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 290, 64, 64));

        label_login.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        label_login.setText("LOGIN");
        getContentPane().add(label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 380, -1, -1));

        label_footer.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        label_footer.setForeground(new java.awt.Color(0, 51, 51));
        label_footer.setText("Desarrollado por Marlon Torres © 2023");
        getContentPane().add(label_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, -1, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar-sesion 32-px.png"))); // NOI18N
        btn_exit.setBorder(null);
        btn_exit.setContentAreaFilled(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 537));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        if (evt.getSource() == btn_exit) {
            int i = JOptionPane.showConfirmDialog(this, "¿Desea salir del Sistema?");
            if (i == 0) {
                System.exit(0);
            } else if (i == 1) {
                JOptionPane.showMessageDialog(this, "Gracias. Continuemos con el programa");
            }
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    
    public static void main(String args[]) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                        Principal frame = new Principal();
                        frame.setVisible(true);
                } catch (Exception e) {
                        e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel label_footer;
    private javax.swing.JLabel label_log;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_wallpaper;
    // End of variables declaration//GEN-END:variables
}
