package views;

import java.awt.Color;
import java.awt.Image;
import java.awt.SystemColor;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import javax.swing.border.LineBorder;
import com.toedter.calendar.JDateChooser;
import controller.HuespedController;
import controller.ReservaController;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import model.Huesped;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTextField;
/**
 *
 * @author marleonii
 */
public class RegistroHuesped extends javax.swing.JFrame {

    String user;
    int userSession = 0, session_user = 0;
    public static JDateChooser txt_birthdate;
    private final HuespedController guestController;
    private final ReservaController reservationController;

    public RegistroHuesped(int idReserva) {
        initComponents();
        user = Login.user;
        this.guestController = new HuespedController();
        this.reservationController = new ReservaController();
        session_user = Administrador.session_user;
        userSession = Capturista.userSession;
        

        setSize(600, 640);
        setResizable(false);
        setTitle("Registrar nuevo Huésped - Sesión de " + user);
        setLocationRelativeTo(null);
        
        ImageIcon log = new ImageIcon("src/images/Ha-100px.png");
        Icon icon_log = new ImageIcon(log.getImage().getScaledInstance(label_log.getWidth(),
                label_log.getHeight(), Image.SCALE_DEFAULT));
        label_log.setIcon(icon_log);
        this.repaint();

        ImageIcon background = new ImageIcon("src/images/login2.png");
        Icon icon_background = new ImageIcon(background.getImage().getScaledInstance(label_background.getWidth(),
                label_background.getHeight(), Image.SCALE_DEFAULT));
        label_background.setIcon(icon_background);
        this.repaint();
        
        if (session_user == 1 || userSession == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }
        
        txt_birthdate = new JDateChooser();
        txt_birthdate.setBackground(Color.WHITE);
        txt_birthdate.getCalendarButton().setIcon(new ImageIcon(
                RegistroHuesped.class.getResource("/images/icon-reservas.png")));
        txt_birthdate.getCalendarButton().setBackground(SystemColor.textHighlight);
        txt_birthdate.getCalendarButton().setFont(new java.awt.Font("Roboto", 1, 12));
        txt_birthdate.getCalendarButton().setBounds(250, 0, 21, 28);
        txt_birthdate.setBorder(new LineBorder(SystemColor.window));
        txt_birthdate.setDateFormatString("yyyy-MM-dd");
        txt_birthdate.setFont(new java.awt.Font("Roboto", 1, 18));
        getContentPane().add(txt_birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(
                30, 360, 250, 30));

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icon);
        this.repaint();
        
        System.out.println(idReserva);
        String ids = String.valueOf(idReserva);
	txt_reservation.setText(ids);
    }


    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icon-40px.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_log = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        label_lastName = new javax.swing.JLabel();
        txt_lastName = new javax.swing.JTextField();
        label_reservation = new javax.swing.JLabel();
        txt_reservation = new javax.swing.JTextField();
        label_birthdate = new javax.swing.JLabel();
        label_nationality = new javax.swing.JLabel();
        jcb_nationality = new javax.swing.JComboBox<>();
        label_phone = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        label_register = new javax.swing.JLabel();
        label_footer = new javax.swing.JLabel();
        label_title = new javax.swing.JLabel();
        label_background = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ha-100px.png"))); // NOI18N
        getContentPane().add(label_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 100, 100));

        label_name.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_name.setForeground(new java.awt.Color(255, 255, 255));
        label_name.setText("Nombre:");
        getContentPane().add(label_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txt_name.setBackground(new java.awt.Color(204, 204, 255));
        txt_name.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_name.setForeground(java.awt.SystemColor.activeCaption);
        txt_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, -1));

        label_lastName.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_lastName.setForeground(new java.awt.Color(255, 255, 255));
        label_lastName.setText("Apellido:");
        getContentPane().add(label_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        txt_lastName.setBackground(new java.awt.Color(204, 204, 255));
        txt_lastName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_lastName.setForeground(java.awt.SystemColor.activeCaption);
        txt_lastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, -1));

        label_reservation.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_reservation.setForeground(new java.awt.Color(255, 255, 255));
        label_reservation.setText("Reserva");
        getContentPane().add(label_reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txt_reservation.setEditable(false);
        txt_reservation.setBackground(new java.awt.Color(204, 204, 255));
        txt_reservation.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_reservation.setForeground(java.awt.SystemColor.activeCaption);
        txt_reservation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 250, -1));

        label_birthdate.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_birthdate.setForeground(new java.awt.Color(255, 255, 255));
        label_birthdate.setText("Fecha de Nacimiento:");
        getContentPane().add(label_birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        label_nationality.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_nationality.setForeground(new java.awt.Color(255, 255, 255));
        label_nationality.setText("Nacionalidad:");
        getContentPane().add(label_nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jcb_nationality.setBackground(new java.awt.Color(204, 204, 255));
        jcb_nationality.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jcb_nationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "afgano-afgana", "alemán-alemana", "árabe-árabe", "argentino-argentina", "australiano-australiana", "belga-belga", "boliviano-boliviana", "brasileño-brasileña", "camboyano-camboyana", "canadiense-canadiense", "chileno-chilena", "chino-china", "colombiano-colombiana", "coreano-coreana", "costarricense-costarricense", "cubano-cubana", "danés-danesa", "ecuatoriano-ecuatoriana", "egipcio-egipcia", "salvadoreño-salvadoreña", "escocés-escocesa", "español-española", "estadounidense-estadounidense", "estonio-estonia", "etiope-etiope", "filipino-filipina", "finlandés-finlandesa", "francés-francesa", "galés-galesa", "griego-griega", "guatemalteco-guatemalteca", "haitiano-haitiana", "holandés-holandesa", "hondureño-hondureña", "indonés-indonesa", "inglés-inglesa", "iraquí-iraquí", "iraní-iraní", "irlandés-irlandesa", "israelí-israelí", "italiano-italiana", "japonés-japonesa", "jordano-jordana", "laosiano-laosiana", "letón-letona", "letonés-letonesa", "malayo-malaya", "marroquí-marroquí", "mexicano-mexicana", "nicaragüense-nicaragüense", "noruego-noruega", "neozelandés-neozelandesa", "panameño-panameña", "paraguayo-paraguaya", "peruano-peruana", "polaco-polaca", "portugués-portuguesa", "puertorriqueño-puertorriqueño", "dominicano-dominicana", "rumano-rumana", "ruso-rusa", "sueco-sueca", "suizo-suiza", "tailandés-tailandesa", "taiwanes-taiwanesa", "turco-turca", "ucraniano-ucraniana", "uruguayo-uruguaya", "venezolano-venezolana", "vietnamita-vietnamita" }));
        getContentPane().add(jcb_nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 250, -1));

        label_phone.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_phone.setForeground(new java.awt.Color(255, 255, 255));
        label_phone.setText("Telefono:");
        getContentPane().add(label_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        txt_phone.setBackground(new java.awt.Color(204, 204, 255));
        txt_phone.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_phone.setForeground(java.awt.SystemColor.activeCaption);
        txt_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 250, -1));

        btn_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_register.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 120, 100));

        label_register.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        label_register.setForeground(java.awt.SystemColor.activeCaptionText);
        label_register.setText("Registrar Huésped");
        getContentPane().add(label_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, -1, -1));

        label_footer.setBackground(new java.awt.Color(102, 102, 102));
        label_footer.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        label_footer.setForeground(new java.awt.Color(102, 102, 102));
        label_footer.setText("Desarrollado por Marlon Torres © 2023");
        getContentPane().add(label_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 610, 242, -1));

        label_title.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        label_title.setForeground(new java.awt.Color(255, 255, 255));
        label_title.setText("Registro de Huésped");
        getContentPane().add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, -1));

        label_background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(label_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 110, 310, 330));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        btn_register.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Save();
            }
        });
    }//GEN-LAST:event_btn_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            java.awt.EventQueue.invokeLater(() -> {
                new RegistroHuesped(0).setVisible(true);
            });
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JComboBox<String> jcb_nationality;
    private javax.swing.JLabel label_background;
    private javax.swing.JLabel label_birthdate;
    private javax.swing.JLabel label_footer;
    private javax.swing.JLabel label_lastName;
    private javax.swing.JLabel label_log;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_nationality;
    private javax.swing.JLabel label_phone;
    private javax.swing.JLabel label_register;
    private javax.swing.JLabel label_reservation;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_reservation;
    // End of variables declaration//GEN-END:variables

    public void Save() {
        String name, lastname, phone, birthdate;
        int validation = 0, reservation;
        
        name = txt_name.getText().trim();
        lastname = txt_lastName.getText().trim();
        phone = txt_phone.getText().trim();
        reservation = Integer.parseInt(txt_reservation.getText());
        birthdate = ((JTextField)txt_birthdate.getDateEditor().getUiComponent()).getText();
        
        if (name.equals("")) {
            txt_name.setBackground(Color.red);
            validation ++;
        }
        if (lastname.equals("")) {
            txt_lastName.setBackground(Color.red);
            validation ++;
        }
        if (phone.equals("")) {
            txt_phone.setBackground(Color.red);
            validation ++;
        }
        
        try {
            if (validation == 0) {
            
                try {
                    Huesped guests = new Huesped(txt_name.getText(), txt_lastName.getText(),
                            txt_phone.getText(), java.sql.Date.valueOf(birthdate),
                            jcb_nationality.getSelectedItem().toString(), reservation);
                this.guestController.Save(guests);

                Clear();
                
                txt_name.setBackground(Color.GREEN);
                txt_lastName.setBackground(Color.GREEN);
                txt_phone.setBackground(Color.GREEN);
                txt_reservation.setBackground(Color.GREEN);
                
                int id_huesped = guests.getId();
                
                try {
                if(id_huesped != 0){
                    reservationController.UpdateHuesped(id_huesped, reservation);
                } else{
                }
            } catch (HeadlessException evt) {
                System.err.println("ERROR al registrar." + evt);
            }
                
                Exito exito = new Exito();
                exito.setVisible(true);
                } catch (Exception e) {
                    System.err.println("ERROR en Registrar Huesped. " + e);
                    JOptionPane.showMessageDialog(null, "¡¡ERROR al registrar!!, contacte al administrador.");
                }   
            } else {
                JOptionPane.showMessageDialog(this, "Debes llenar todos los campos.");
            }
        } catch (HeadlessException e) {
            throw e;
        }
        
    }
    
    public void Clear() {
        txt_name.setText("");
        txt_lastName.setText("");
        txt_phone.setText("");
        txt_reservation.setText("");
        txt_birthdate.setDateFormatString("yyyy-MM-dd");
        
    }
}
